### ISSUE TITLE
Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

### ISSUE THREAD

**Issue by Defuera** [Manabu-GT/ExpandableTextView#11]
I resolved this by commenting 
// for maven central deployment
//apply from: 'https://raw.githubusercontent.com/chrisbanes/gradle-mvn-push/master/gradle-mvn-push.gradle'
in build.gradle of lib module

**Comment by Manabu-GT** [comment]
The fix is in the master branch now.

**Comment by kirsong** [comment]
Thank you. I've been in the same situation

**Comment by SandeepPinninti** [comment]
###s # s# s#s ## ### s
