### ISSUE TITLE
Expand Collapse Icons not visible

### ISSUE THREAD

**Issue by vrvmadan** [Manabu-GT/ExpandableTextView#13]
when i tried to implement the expandable text-view in a list view The expand and collapse icons are not appearing could you please help me out if i am doing wrong 

MyCode: List_rowitem

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:expandableTextView="http://schemas.android.com/apk/res-auto"
    android:layout_width="fill_parent"
    android:layout_height="wrap_content"
    android:background="#B3433618"
    android:orientation="horizontal"
    android:descendantFocusability="blocksDescendants"
    android:padding="5dip" >
 
    
    <LinearLayout android:id="@+id/thumbnail"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:padding="3dip"
        android:layout_alignParentLeft="true"
        android:background="@android:color/transparent"
        android:layout_marginRight="5dp">
 
        <ImageView
            android:id="@+id/list_image"
            android:contentDescription="@string/app_name"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:background="@drawable/imagebordercolor"
            />
 
    </LinearLayout>
 
    

    <TextView
        android:id="@+id/title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignTop="@+id/thumbnail"
        android:layout_toRightOf="@+id/thumbnail"
        android:textColor="@android:color/white"
        android:textSize="15sp"
        android:textStyle="bold"
        android:typeface="sans" />
 
    
    <com.fiveytechnologies.bhagavadgita.views.ExpandableTextView 
        android:id="@+id/expand_text_view"
        android:layout_width="fill_parent"
        android:layout_height="wrap_content"
        android:layout_below="@id/title"
        android:focusable="false"
        android:focusableInTouchMode="false"
        android:layout_marginTop="1dip"
        android:layout_toRightOf="@+id/thumbnail"
        expandableTextView:maxCollapsedLines="8"
        expandableTextView:animAlphaStart="1"
        >
        
       <TextView
            android:id="@id/expandable_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="4dp"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:textSize="12sp"
            android:textColor="@android:color/white" />

        <ImageButton
            android:id="@id/expand_collapse"
            android:contentDescription="@string/app_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="1dp"
            android:layout_gravity="right|bottom"
            android:background="@android:color/transparent"/>
        
        
     </com.fiveytechnologies.bhagavadgita.views.ExpandableTextView>
    
    
    
      
 
    
    <TextView
        android:id="@+id/duration"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentRight="true"
        android:layout_alignTop="@id/title"
        android:gravity="right"
        android:text="@string/slokacount"
        android:layout_marginRight="5dip"
        android:textSize="12sp"
        android:textColor="#10bcc9"
        android:textStyle="bold"
        android:visibility="gone"
        />
 
     
   
 
</RelativeLayout>

**Comment by Chesteer89** [comment]
When you don't expect a license, don't expect a help (com.fiveytechnologies.bhagavadgita.views.ExpandableTextView ).

Maybe your text is just too small to show collapse/expand icon?

**Comment by Manabu-GT** [comment]
Did you set the long enough texts for the expandable text?
Since your maxCollapsedLines attribute is 8, you need to have more than 8 lines of text for the expand icon to be shown.

**Comment by SethFeng** [comment]
@vrvmadan 
The orientation of ExpandableTextView is horizontal, and your TextView's layout_width is match_parent. ImageButton has no space.
