### ISSUE TITLE
Extra blank space when expanded inside RecyclerView

### ISSUE THREAD

**Issue by slidenerd** [Manabu-GT/ExpandableTextView#26]
Hi Manabu-GT, I am using a slightly modified version of your library, the only modification I did was to remove the drawable for expand and collapse and replace that with a TextView instead so that it shows Read More and Read Less
![testgif](https://cloud.githubusercontent.com/assets/5139030/10863345/612d58d0-7ff0-11e5-8ffc-214a018c0528.gif)

When I expand an item in the RecyclerView and scroll down and come back up, I find it collapsed, I also find extra blank spaces scattered everywhere, am I missing something? Also as per the GIF if you notice, it doesn't expand another time. Thanks for your suggestions in advance

**Comment by slidenerd** [comment]
Never mind, I fixed it, i was calling the wrong setText method without using a Sparse Boolean Array, thanks for your library

**Comment by DigaoParceiro** [comment]
My solution was delete the `expandableTextView:maxCollapsedLines` line from the xml
