### ISSUE TITLE
After expanding, it does not show last few lines

### ISSUE THREAD

**Issue by faraz-ahmad** [Manabu-GT/ExpandableTextView#5]
When we expand textview, it is not showing last few lines because getRealTextViewHeight function is not giving correct textview height.I think it should be called on the right place.Please look into this.

**Comment by Chesteer89** [comment]
It's exists also, when you used cusom font. In my situation i used Calligraphy lib (https://github.com/chrisjenx/Calligraphy). It's strange, because when i expand selected textview, it does not shown last line, but when i scroll it in container (listview) the view is recreated fine - last line appears. Any ideas?

**Comment by Chesteer89** [comment]
Interesting. With android:orientation="vertical" everything looks fine, in horizontal there's a bug with last line.

Assuming:
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:expandableTextView="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <com.ms.square.android.expandabletextview.ExpandableTextView
        android:id="@+id/expand_text_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical"
        expandableTextView:maxCollapsedLines="0"
        expandableTextView:animAlphaStart="1"
        expandableTextView:expandDrawable="@drawable/arrow_small"
        expandableTextView:collapseDrawable="@drawable/arrow_small_bottom">

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">
        <TextView
            android:id="@+id/expandable_text_title"
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginLeft="10dp"
            style="@style/TextAppearance.Medium"
            android:textStyle="bold"
            android:text="TITLE"
            android:textColor="@color/dark_gray"
            android:clickable="true"
            tools:ignore="MissingPrefix" />

        <ImageButton
            android:id="@id/expand_collapse"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="12dp"
            android:layout_gravity="center"
            android:background="@android:color/transparent"/>

        </LinearLayout>
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">
            <TextView
                android:id="@id/expandable_text"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:paddingTop="8dp"
                android:paddingLeft="10dp"
                android:paddingRight="10dp"
                android:paddingBottom="10dp"
                style="@style/TextAppearance.Subhead"
                android:textSize="13dp"
                android:text="Description"
                android:textColor="@color/dark_gray" />

            <ImageButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:padding="12dp"
                android:layout_gravity="center"
                android:visibility="invisible"
                android:background="@android:color/transparent"/>
        </LinearLayout>
    </com.ms.square.android.expandabletextview.ExpandableTextView>

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:src="@drawable/separator"
        android:paddingLeft="10dp"
        android:paddingRight="10dp"/>
</LinearLayout>

works fine, following:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:expandableTextView="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <com.ms.square.android.expandabletextview.ExpandableTextView
        android:id="@+id/expand_text_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        expandableTextView:maxCollapsedLines="0"
        expandableTextView:animAlphaStart="1"
        expandableTextView:expandDrawable="@drawable/arrow_small"
        expandableTextView:collapseDrawable="@drawable/arrow_small_bottom">

        <LinearLayout
            android:layout_width="0dp"
            android:layout_weight="1"
            android:layout_height="wrap_content"
            android:orientation="vertical">
        <TextView
            android:id="@+id/expandable_text_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginLeft="10dp"
            style="@style/TextAppearance.Medium"
            android:textStyle="bold"
            android:text="TITLE"
            android:textColor="@color/dark_gray"
            android:clickable="true"
            tools:ignore="MissingPrefix" />
        <TextView
            android:id="@id/expandable_text"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="8dp"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:layout_marginBottom="10dp"
            style="@style/TextAppearance.Subhead"
            android:textSize="13dp"
            android:text="Description"
            android:textColor="@color/dark_gray" />
        </LinearLayout>
        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical">
        <ImageButton
            android:id="@id/expand_collapse"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:padding="12dp"
            android:layout_marginTop="20dp"
            android:layout_gravity="center"
            android:background="@android:color/transparent"/>

        </LinearLayout>
    </com.ms.square.android.expandabletextview.ExpandableTextView>

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="2dp"
        android:src="@drawable/separator"
        android:paddingLeft="10dp"
        android:paddingRight="10dp"/>
</LinearLayout>

has an bug with last line.

**Comment by MARGI3** [comment]
i got this problem too

**Comment by payaswini** [comment]
How can we make text in expandabletextview to bold?Please give me the solution

**Comment by qinxianyuzou** [comment]
I also encountered the same problem. After the super.onMeasure method, the lineCount obtained by the textview is incorrect, resulting in incorrect calculation height.

**Comment by harismuneer** [comment]
Incase of large text, the text isn't shown completely in expanded state. The solution suggested by @faraz-ahmad will work for every situation no matter how long the text is in the text view as compared to the addition of padding solution by @MARGI3 since you can't decide how much padding to add in order to fully display the text.

Trust me, I have spent two days working on this bug since in my case the text in the textview was quite large.  This is still a bug in the latest version of this repository as of now. Following is the solution explained clearly.

### **SOLUTION**

In ExpandableTextView class, in the **onMeasure** method: Cut the line 

```
       mTextHeightWithMaxLines = getRealTextViewHeight(mTv);

```
and paste it right below this line 

```      // Re-measure with new setup
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);
``` 

Or for ease, you can directly replace your **onMeasure** method with the method below.

```  kotlin   
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        // If no change, measure and return
        if (!mRelayout || getVisibility() == View.GONE) {
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
            return;
        }
        mRelayout = false;

        // Setup with optimistic case
        // i.e. Everything fits. No button needed
        mToggleView.setVisibility(View.GONE);
        mTv.setMaxLines(Integer.MAX_VALUE);

        // Measure
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

        //--- Previously the mTextHeightWithMaxLines was initialized here ---//       

        // If the text fits in collapsed mode, we are done.
        if (mTv.getLineCount() <= mMaxCollapsedLines) {
            return;
        }

        // Doesn't fit in collapsed mode. Collapse text view as needed. Show
        // button.
        if (mCollapsed) {
            mTv.setMaxLines(mMaxCollapsedLines);
        }
        mToggleView.setVisibility(View.VISIBLE);

        // Re-measure with new setup
        super.onMeasure(widthMeasureSpec, heightMeasureSpec);

       mTextHeightWithMaxLines = getRealTextViewHeight(mTv);

        if (mCollapsed) {
            // Gets the margin between the TextView's bottom and the ViewGroup's bottom
            mTv.post(new Runnable() {
                @Override
                public void run() {
                    mMarginBetweenTxtAndBottom = getHeight() - mTv.getHeight();
                }
            });
            // Saves the collapsed height of this ViewGroup
            mCollapsedHeight = getMeasuredHeight();
        }
    } 
```
