### ISSUE TITLE
Can't build with Gradle

### ISSUE THREAD

**Issue by tundebabzy** [Manabu-GT/ExpandableTextView#8]
I use Intellij Idea for android development. I have not been able to build the app with Gradle. I get this error:
No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

**Comment by hisham2007** [comment]
I face the same issue with Android Studio.. please help

**Comment by tundebabzy** [comment]
@hisham2007 Are you getting the same error message? I can't remember encountering issues with Android Studio.

**Comment by hisham2007** [comment]
the issue was with sample app. I imported library project successfully and used it

**Comment by Manabu-GT** [comment]
@hisham2007 Are you still having the issue? I use Android Studio 1.0.2 locally, and currently have no issue building the sample app.

**Comment by Manabu-GT** [comment]
@hisham2007 plz reopen if u are still experiencing the issue.
