### ISSUE TITLE
Hard coded id in XML layout

### ISSUE THREAD

**Issue by tundebabzy** [Manabu-GT/ExpandableTextView#9]
mTv = (TextView) findViewById(R.id.expandable_text);
    mButton = (ImageButton) findViewById(R.id.expand_collapse);

These lines in `findViews` mean that the id for the children of ExpandableTextView *must* be `expandable_text` and `expandand_collapse` for the TextView and ImageButton respectively.  

I initially changed the ids in my XML layout and slammed into a null-pointer exception until i dug into the code. It will nice if this "limitation" is made known to users or better still, remove the hard coded ids. I can submit a pull request to remove the hard coded ids.

**Comment by Manabu-GT** [comment]
It will nice if this "limitation" is made known to users or better still, remove the hard coded ids.
-> sorry for confusion, I will clarify that fact on the README.

**Comment by Manabu-GT** [comment]
README just updated to mention this limitation.
